"""TDD: requirement extraction must walk every CONTENT section of a
``main.md`` (not just index leaves) and tag each with the document's own
top-level chapter heading as its category.

This is what lets dense engineering PRDs -- whose requirement summary
tables sit under mid-level headings -- be extracted completely.
"""

from __future__ import annotations

from pathlib import Path

from kb_extract.wiki.requirements.sections import (
    ContentSection,
    chunk_body,
    iter_content_sections,
)

_MAIN_MD = """<!-- generated by kb-extract; do not edit; source_sha256: deadbeef -->

<a id="sec-0001"></a>
# Mechanical & Industrial Design

<a id="sec-0002"></a>
## Hinge

The hinge shall withstand 30N of force without visible deflection.

<a id="tbl-0001"></a>
<table><tr><td>Force</td><td>30N</td></tr></table>

<a id="sec-0003"></a>
## Typing Rigidity

Keyset shall not flex more than 0.5mm under 10N load.

<a id="sec-0004"></a>
# Electrical

The system shall operate between 4.5V and 5.5V.
"""


def _write_kb(tmp_path: Path) -> Path:
    kb = tmp_path / "kb"
    doc = kb / "DocA"
    doc.mkdir(parents=True)
    (doc / "main.md").write_text(_MAIN_MD, encoding="utf-8")
    return kb


def test_iter_skips_heading_only_parents(tmp_path: Path) -> None:
    kb = _write_kb(tmp_path)
    sections = iter_content_sections(kb, "DocA")
    anchors = [s.anchor for s in sections]
    # sec-0001 (# Mechanical...) is a heading-only parent -> skipped.
    assert "sec-0001" not in anchors
    # The three content sections are all present.
    assert anchors == ["sec-0002", "sec-0003", "sec-0004"]


def test_category_is_top_level_ancestor(tmp_path: Path) -> None:
    kb = _write_kb(tmp_path)
    by_anchor = {s.anchor: s for s in iter_content_sections(kb, "DocA")}
    assert by_anchor["sec-0002"].category == "Mechanical & Industrial Design"
    assert by_anchor["sec-0003"].category == "Mechanical & Industrial Design"
    # A level-1 section that carries its own body uses its own title.
    assert by_anchor["sec-0004"].category == "Electrical"


def test_body_includes_tables_and_excludes_heading(tmp_path: Path) -> None:
    kb = _write_kb(tmp_path)
    by_anchor = {s.anchor: s for s in iter_content_sections(kb, "DocA")}
    hinge = by_anchor["sec-0002"]
    assert "## Hinge" not in hinge.body
    assert "30N" in hinge.body
    assert "<table>" in hinge.body  # the table anchor/body stays in section


def test_titles_and_levels(tmp_path: Path) -> None:
    kb = _write_kb(tmp_path)
    by_anchor = {s.anchor: s for s in iter_content_sections(kb, "DocA")}
    assert by_anchor["sec-0002"].title == "Hinge"
    assert by_anchor["sec-0002"].level == 2
    assert by_anchor["sec-0004"].level == 1


def test_missing_doc_returns_empty(tmp_path: Path) -> None:
    kb = tmp_path / "kb"
    kb.mkdir()
    assert iter_content_sections(kb, "NoSuchDoc") == []


def test_chunk_body_no_truncation_round_trips() -> None:
    paragraphs = [f"Paragraph number {i} with some content." for i in range(200)]
    body = "\n\n".join(paragraphs)
    chunks = chunk_body(body, max_chars=500)
    assert len(chunks) > 1
    # Every chunk is within budget...
    assert all(len(c) <= 500 for c in chunks)
    # ...and no content is lost (every paragraph survives somewhere).
    joined = "\n\n".join(chunks)
    for p in paragraphs:
        assert p in joined


def test_chunk_body_single_when_small() -> None:
    body = "short body"
    assert chunk_body(body, max_chars=500) == ["short body"]


def test_content_section_is_frozen() -> None:
    s = ContentSection(
        anchor="sec-0001", title="T", level=1, category="C", body="b"
    )
    assert s.anchor == "sec-0001"
