"""Test-only adapter: trivially valid ExtractionResult for any input.

Registered manually in tests; NOT auto-registered to the default registry.
Useful for orchestrator/hardness wiring tests without real document parsing.
"""

from __future__ import annotations

import hashlib
from datetime import UTC, datetime
from pathlib import Path

from ..contracts import ExtractionMeta, ExtractionResult, SectionNode


class NoopAdapter:
    name = "_noop"
    version = "0.1"
    extensions = (".noop",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        data = src.read_bytes()
        sha = hashlib.sha256(data).hexdigest()
        leaf = SectionNode(
            node_id="0001",
            title="Noop content",
            level=1,
            page_start=1,
            page_end=1,
            anchor="sec-0001",
            language="und",
        )
        root = SectionNode(
            node_id="0000",
            title="Root",
            level=0,
            page_start=1,
            page_end=1,
            anchor="",
            language="und",
            children=(leaf,),
        )
        markdown = (
            f'<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->\n\n'
            '<a id="sec-0001"></a>\n'
            '# Noop content\n\n'
            f'(noop adapter for tests: {src.name})\n'
        )
        meta = ExtractionMeta(
            source_path=src.name,
            source_sha256=sha,
            source_bytes=len(data),
            source_mtime_iso=datetime.fromtimestamp(
                src.stat().st_mtime, tz=UTC
            ).isoformat(),
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={},
            extracted_at_iso="2026-06-09T00:00:00+00:00",
            outline_source="bookmark",
            status="ok",
            warnings=(),
            skipped_reasons=(),
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=(), assets=(), meta=meta
        )
