"""DOCX adapter using python-docx. Spec §6 row 'docx'."""

from __future__ import annotations

import hashlib
from pathlib import Path

import docx as _docx  # python-docx
import langdetect

from ..contracts import ExtractionResult, SectionNode, TableRef
from ._common import make_meta

_DOCX_VERSION = getattr(_docx, "__version__", "unknown")

_HEADING_LEVELS = {
    "Heading 1": 1,
    "Heading 2": 2,
    "Heading 3": 3,
    "Heading 4": 4,
}


def _detect_lang(text: str) -> str:
    try:
        return langdetect.detect(text) if text.strip() else "und"
    except Exception:
        return "und"


class DocxAdapter:
    name = "docx"
    version = "0.1"
    extensions = (".docx",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        doc = _docx.Document(str(src))

        md_lines: list[str] = []
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        md_lines.append(
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->"
        )
        md_lines.append("")

        children: list[SectionNode] = []
        tables: list[TableRef] = []
        warnings: list[str] = []
        anchor_counter = 0
        table_counter = 0
        body_text_acc: list[str] = []

        def next_anchor() -> str:
            nonlocal anchor_counter
            anchor_counter += 1
            return f"sec-{anchor_counter:04d}"

        # Track section stack for hierarchical nesting.
        section_stack: list[SectionNode] = []
        node_counter = 0

        # Walk top-level paragraphs and tables in document order.
        for block in _iter_blocks(doc):
            if block.__class__.__name__ == "Paragraph":
                style = block.style.name if block.style else ""
                level = _HEADING_LEVELS.get(style)
                if level:
                    node_counter += 1
                    anchor = next_anchor()
                    new_section = SectionNode(
                        node_id=f"{node_counter:04d}",
                        title=block.text.strip() or "(untitled)",
                        level=level,
                        page_start=1,
                        page_end=1,
                        anchor=anchor,
                        language="und",
                        children=(),
                    )
                    md_lines.append(f'<a id="{anchor}"></a>')
                    md_lines.append(f"{'#' * level} {block.text.strip()}")
                    md_lines.append("")

                    # Maintain hierarchical nesting.
                    while section_stack and section_stack[-1].level >= level:
                        section_stack.pop()

                    if section_stack:
                        parent = section_stack[-1]
                        section_stack[-1] = SectionNode(
                            node_id=parent.node_id, title=parent.title, level=parent.level,
                            page_start=parent.page_start, page_end=parent.page_end,
                            anchor=parent.anchor, language=parent.language,
                            children=tuple([*parent.children, new_section]),
                        )
                    else:
                        children.append(new_section)

                    section_stack.append(new_section)
                elif style and style not in {"Normal", "Default Paragraph Font"}:
                    if style not in _HEADING_LEVELS:
                        warnings.append(f"docx.unknown_style:{style}")
                    md_lines.append(block.text)
                    md_lines.append("")
                    body_text_acc.append(block.text)
                else:
                    if block.text.strip():
                        md_lines.append(block.text)
                        md_lines.append("")
                        body_text_acc.append(block.text)
            elif block.__class__.__name__ == "Table":
                table_counter += 1
                t_anchor = f"tbl-{table_counter:04d}"
                rows: list[tuple[str, ...]] = []
                for row in block.rows:
                    rows.append(tuple(cell.text for cell in row.cells))
                md_lines.append(f'<a id="{t_anchor}"></a>')
                md_lines.append(_render_table_md(rows))
                md_lines.append("")
                tables.append(TableRef(
                    anchor=t_anchor, page=1, rows_json=tuple(rows),
                    rendered_asset=None,
                ))

        if not children:
            # Page-fallback: one synthetic section so H4/H9 hold.
            anchor = next_anchor()
            children.append(SectionNode(
                node_id="0001", title=src.stem, level=1,
                page_start=1, page_end=1, anchor=anchor, language="und",
            ))
            md_lines.insert(2, f'<a id="{anchor}"></a>')
            md_lines.insert(3, f"# {src.stem}")
            md_lines.insert(4, "")
            outline_source = "page_fallback"
        else:
            outline_source = "heading_style"

        lang = _detect_lang(" ".join(body_text_acc))
        root = SectionNode(
            node_id="0000", title=src.stem, level=0, page_start=1, page_end=1,
            anchor="", language=lang, children=tuple(children),
        )
        # Update children language uniformly (v1 simplification).
        root = _set_language(root, lang)

        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"python-docx": _DOCX_VERSION},
            outline_source=outline_source,
            warnings=tuple(warnings),
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=tuple(tables), assets=(), meta=meta
        )


def _iter_blocks(doc):
    """Yield Paragraph / Table objects in document order."""
    from docx.oxml.ns import qn
    body = doc.element.body
    for child in body.iterchildren():
        if child.tag == qn("w:p"):
            yield doc.paragraphs[[p._element for p in doc.paragraphs].index(child)]
        elif child.tag == qn("w:tbl"):
            yield doc.tables[[t._element for t in doc.tables].index(child)]


def _render_table_md(rows: list[tuple[str, ...]]) -> str:
    if not rows:
        return ""
    header = rows[0]
    body = rows[1:]
    lines = []
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for r in body:
        # Pad/truncate to header width.
        cells = list(r) + [""] * (len(header) - len(r))
        lines.append("| " + " | ".join(cells[: len(header)]) + " |")
    return "\n".join(lines)


def _set_language(node: SectionNode, lang: str) -> SectionNode:
    return SectionNode(
        node_id=node.node_id, title=node.title, level=node.level,
        page_start=node.page_start, page_end=node.page_end,
        anchor=node.anchor, language=lang,
        children=tuple(_set_language(c, lang) for c in node.children),
    )
