"""Image adapter: PNG/JPG/JPEG. Single section per image. Spec §6."""

from __future__ import annotations

import shutil
from pathlib import Path

from PIL import Image as PILImage

from ..contracts import AssetRef, ExtractionResult, SectionNode
from ._common import make_meta, sha256_file

_PIL_VERSION = getattr(PILImage, "__version__", "unknown")


class ImageAdapter:
    name = "image"
    version = "0.1"
    extensions = (".png", ".jpg", ".jpeg")

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        # 1. Copy raw bytes (no re-encoding).
        dest_name = src.name
        dest = out_dir_tmp / "assets" / dest_name
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)
        sha = sha256_file(dest)

        # 2. Read dimensions via Pillow (no network).
        with PILImage.open(dest) as im:
            w, h = im.size

        # 3. Build single-section tree.
        leaf = SectionNode(
            node_id="0001",
            title=src.stem,
            level=1,
            page_start=1,
            page_end=1,
            anchor="sec-0001",
            language="und",
        )
        root = SectionNode(
            node_id="0000",
            title=src.stem,
            level=0,
            page_start=1,
            page_end=1,
            anchor="",
            language="und",
            children=(leaf,),
        )
        markdown = (
            f'<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->\n\n'
            f'<a id="sec-0001"></a>\n'
            f'# {src.stem}\n\n'
            f'![{src.stem}](assets/{dest_name})\n'
        )
        asset = AssetRef(
            kind="image", rel_path=f"assets/{dest_name}",
            page=1, sha256=sha, width=w, height=h, alt=src.stem,
        )
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"Pillow": _PIL_VERSION},
            outline_source="page_fallback",
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=(), assets=(asset,), meta=meta
        )
