"""PDF adapter. Bookmark-first via pymupdf; docling-layout fallback planned.

For v1: pymupdf bookmarks → section tree; raw text extracted per page;
embedded images saved verbatim. docling integration deferred for v1.1
because docling first-run model download is heavy and may not be
bit-identical (spec §10 risk).
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import fitz  # pymupdf

from ..contracts import AssetRef, ExtractionResult, SectionNode
from ._common import make_meta, sha256_bytes


class PdfDoclingAdapter:
    name = "pdf_docling"
    version = "0.1"
    extensions = (".pdf",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        doc = fitz.open(str(src))
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        md_lines: list[str] = [
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->",
            "",
        ]
        page_texts: list[str] = []
        warnings: list[str] = []
        # Per-page raw text
        for page in doc:
            try:
                page_texts.append(page.get_text("text") or "")
            except Exception:
                page_texts.append("")
                warnings.append(f"pdf.font_decode_failed:p{page.number + 1}")

        n_pages = doc.page_count
        toc = doc.get_toc(simple=True)  # [[level, title, page], ...]
        children: list[SectionNode] = []
        outline_source: str

        if toc:
            outline_source = "bookmark"
            # Build flat children list at level=1; group multi-page ranges.
            # toc page numbers are 1-based.
            sorted_toc = [t for t in toc if t[2] >= 1]
            sorted_toc.sort(key=lambda t: t[2])
            for i, entry in enumerate(sorted_toc):
                _level, title, start_page = entry
                end_page = (
                    sorted_toc[i + 1][2] - 1 if i + 1 < len(sorted_toc) else n_pages
                )
                anchor = f"sec-{i + 1:04d}"
                md_lines.append(f'<a id="{anchor}"></a>')
                md_lines.append(f"# {title}")
                md_lines.append("")
                for p in range(start_page, end_page + 1):
                    txt = page_texts[p - 1].strip()
                    if txt:
                        md_lines.append(txt)
                        md_lines.append("")
                children.append(SectionNode(
                    node_id=f"{i + 1:04d}", title=title, level=1,
                    page_start=start_page, page_end=end_page,
                    anchor=anchor, language="und",
                ))
        else:
            outline_source = "page_fallback"
            for p in range(1, n_pages + 1):
                anchor = f"sec-{p:04d}"
                md_lines.append(f'<a id="{anchor}"></a>')
                md_lines.append(f"# Page {p}")
                md_lines.append("")
                if page_texts[p - 1].strip():
                    md_lines.append(page_texts[p - 1].strip())
                    md_lines.append("")
                children.append(SectionNode(
                    node_id=f"{p:04d}", title=f"Page {p}", level=1,
                    page_start=p, page_end=p, anchor=anchor, language="und",
                ))

        # Embedded images via pymupdf (raw bytes, no re-encoding).
        assets: list[AssetRef] = []
        assets_dir = out_dir_tmp / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)
        for page_idx in range(n_pages):
            page = doc.load_page(page_idx)
            for img_idx, img in enumerate(page.get_images(full=True), start=1):
                xref = img[0]
                try:
                    info = doc.extract_image(xref)
                except Exception:
                    warnings.append(f"pdf.font_decode_failed:p{page_idx + 1}")
                    continue
                ext = info.get("ext", "png")
                data = info["image"]
                fname = f"p{page_idx + 1}-img{img_idx}.{ext}"
                (assets_dir / fname).write_bytes(data)
                # Find the markdown section for this page and append the image ref.
                # Simpler: append all image refs after their section heading line.
                # For determinism, we insert after the heading of the matching page.
                ref_line = f"![{fname}](assets/{fname})"
                _insert_image_after_page(md_lines, page_idx + 1, ref_line)
                assets.append(AssetRef(
                    kind="image", rel_path=f"assets/{fname}",
                    page=page_idx + 1, sha256=sha256_bytes(data),
                    alt=fname,
                ))

        if any(not pt.strip() for pt in page_texts) and all(
            not pt.strip() for pt in page_texts
        ):
            # Heuristic: if no text on any page, mark scanned warning.
            warnings.append("pdf.scanned_no_text_layer")

        root = SectionNode(
            node_id="0000", title=src.stem, level=0,
            page_start=1, page_end=n_pages,
            anchor="", language="und", children=tuple(children),
        )
        doc.close()
        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"pymupdf": fitz.__doc__ or "unknown"},
            outline_source=outline_source,  # type: ignore[arg-type]
            warnings=tuple(sorted(set(warnings))),
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=(), assets=tuple(assets), meta=meta
        )


def _insert_image_after_page(md_lines: list[str], page: int, ref_line: str) -> None:
    """Insert `ref_line` after the heading matching this page.

    Page anchor convention: `sec-{page:04d}` when in page_fallback mode, or
    the first heading whose section span includes this page. v1 keeps it
    simple: insert after the first `<a id="sec-xxxx"></a>` whose number
    matches the page; if not found, append at end.
    """
    needle = f'<a id="sec-{page:04d}"></a>'
    for i, line in enumerate(md_lines):
        if line == needle:
            # Insert two lines after (after the heading line).
            insert_at = min(i + 3, len(md_lines))
            md_lines.insert(insert_at, ref_line)
            md_lines.insert(insert_at + 1, "")
            return
    md_lines.append(ref_line)
    md_lines.append("")
