"""PDF v2 adapter — MinerU-inspired (v0.8.0 parser v2, spec sec.4.4).

Additions over the legacy ``PdfDoclingAdapter``:

  1. Header/footer dedup: lines that repeat on >= half the pages are
     stripped before body text is emitted. Pure heuristic, fully
     deterministic.
  2. Tables: ``page.find_tables()`` is called for each page; detected
     tables are rendered as HTML via :func:`._table_utils.cells_to_html`
     with the same colspan/rowspan support.
  3. Per-page scanned warning: pages with under 50 non-whitespace
     characters of text get a ``pdf.scanned_page:pN`` warning so the
     user knows OCR would help. The legacy "all pages empty" warning is
     also retained.
  4. Image extraction goes through :func:`._image_utils.save_image`
     (with the magic-byte sniff and >= 1 KiB threshold) so the asset
     naming is uniform across the four v2 adapters.

TOC / heading-inference / page-fallback structure is reused from the
legacy module to keep the surface area small.
"""
from __future__ import annotations

import hashlib
from collections import Counter
from pathlib import Path

import fitz  # pymupdf

from ..contracts import AssetRef, ExtractionResult, SectionNode, TableRef
from ._common import make_meta, sha256_bytes
from ._image_utils import save_image
from ._table_utils import CellInfo, cells_to_html
from .pdf_docling import (
    _build_pdf_page_fallback,
    _build_pdf_tree_from_inferred,
    _build_pdf_tree_from_toc,
)
from .pdf_heading_infer import infer_headings

# Below this many non-whitespace chars on a page -> probable scanned image.
_SCANNED_CHAR_THRESHOLD = 50


def _detect_running_lines(
    page_texts: list[str], threshold: float = 0.5
) -> set[str]:
    """Return non-empty text lines that appear on >= threshold * n_pages pages.

    A line counts once per page (set-based) so a header repeated three
    times on one page does not inflate its score. Single-page documents
    return an empty set (nothing is "running").
    """
    n = len(page_texts)
    if n < 2:
        return set()
    counts: Counter[str] = Counter()
    for txt in page_texts:
        seen: set[str] = set()
        for raw in txt.splitlines():
            line = raw.strip()
            if not line:
                continue
            if line in seen:
                continue
            seen.add(line)
            counts[line] += 1
    cutoff = max(2, int(n * threshold + 0.999))  # ceil
    return {line for line, c in counts.items() if c >= cutoff}


def _strip_lines(text: str, drop: set[str]) -> str:
    if not drop:
        return text
    kept = [line for line in text.splitlines() if line.strip() not in drop]
    return "\n".join(kept).strip("\n")


def _table_to_grid(table) -> list[list[CellInfo]]:
    """Convert a pymupdf Table object to a phantom-free CellInfo grid.

    pymupdf's table extraction returns a 2D list of strings via
    ``table.extract()``; it does not currently expose merged-cell info
    on synthetic PDFs, so colspan/rowspan default to 1.
    """
    rows = table.extract()
    out: list[list[CellInfo]] = []
    for row in rows:
        out_row: list[CellInfo] = []
        for cell in row:
            text = "" if cell is None else str(cell).strip()
            out_row.append(CellInfo(text=text, colspan=1, rowspan=1))
        out.append(out_row)
    return out


class PdfV2Adapter:
    name = "pdf_v2"
    version = "0.8.0"
    extensions = (".pdf",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        doc = fitz.open(str(src))
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        md_lines: list[str] = [
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->",
            "",
        ]

        n_pages = doc.page_count
        warnings: list[str] = []

        # 1. Raw text per page, plus header/footer dedup
        raw_texts: list[str] = []
        for page in doc:
            try:
                raw_texts.append(page.get_text("text") or "")
            except Exception:
                raw_texts.append("")
                warnings.append(f"pdf.font_decode_failed:p{page.number + 1}")
        running = _detect_running_lines(raw_texts, threshold=0.5)
        page_texts = [_strip_lines(t, running) for t in raw_texts]

        # 2. Per-page scanned warning
        for i, txt in enumerate(page_texts, start=1):
            nonws = len("".join(txt.split()))
            if nonws < _SCANNED_CHAR_THRESHOLD:
                warnings.append(f"pdf.scanned_page:p{i}")

        # 3. Section tree (reuse legacy logic)
        toc = doc.get_toc(simple=True)
        outline_source: str
        outline_confidence: str = "high"
        if toc:
            outline_source = "bookmark"
            children = _build_pdf_tree_from_toc(toc, n_pages, page_texts, md_lines)
        else:
            inferred = infer_headings(doc)
            if inferred and inferred.headings:
                outline_source = "heading_inferred"
                outline_confidence = inferred.confidence
                children = _build_pdf_tree_from_inferred(
                    inferred, n_pages, page_texts, md_lines
                )
            else:
                outline_source = "page_fallback"
                outline_confidence = "low"
                children = _build_pdf_page_fallback(n_pages, page_texts, md_lines)

        # 4. Tables per page (appended after the per-page heading anchors)
        tables_out: list[TableRef] = []
        table_count = 0
        for page_idx in range(n_pages):
            page = doc.load_page(page_idx)
            try:
                finder = page.find_tables()
                tables = getattr(finder, "tables", None) or list(finder)
            except Exception:
                tables = []
            for tbl in tables:
                try:
                    grid = _table_to_grid(tbl)
                except Exception:
                    continue
                if not grid:
                    continue
                table_count += 1
                t_anchor = f"tbl-{table_count:04d}"
                _insert_after_page_anchor(
                    md_lines, page_idx + 1,
                    f'<a id="{t_anchor}"></a>',
                    cells_to_html(grid),
                )
                tables_out.append(TableRef(
                    anchor=t_anchor, page=page_idx + 1,
                    rows_json=tuple(tuple(c.text for c in r) for r in grid),
                    rendered_asset=None,
                ))

        # 5. Images via shared helper
        assets: list[AssetRef] = []
        assets_dir = out_dir_tmp / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)
        for page_idx in range(n_pages):
            page = doc.load_page(page_idx)
            for img_idx, img in enumerate(page.get_images(full=True), start=1):
                xref = img[0]
                try:
                    info = doc.extract_image(xref)
                except Exception:
                    warnings.append(f"pdf.font_decode_failed:p{page_idx + 1}")
                    continue
                data = info["image"]
                rel = save_image(
                    data, out_dir_tmp,
                    prefix=f"page_{page_idx + 1}_img",
                    index=img_idx,
                )
                if rel is None:
                    continue
                _insert_after_page_anchor(
                    md_lines, page_idx + 1, f"![]({rel})", ""
                )
                assets.append(AssetRef(
                    kind="image", rel_path=rel,
                    page=page_idx + 1, sha256=sha256_bytes(data),
                    alt="",
                ))

        if all(not pt.strip() for pt in raw_texts):
            warnings.append("pdf.scanned_no_text_layer")

        root = SectionNode(
            node_id="0000", title=src.stem, level=0,
            page_start=1, page_end=n_pages,
            anchor="", language="und", children=children,
        )
        doc.close()
        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"pymupdf": fitz.__doc__ or "unknown"},
            outline_source=outline_source,  # type: ignore[arg-type]
            outline_confidence=outline_confidence,  # type: ignore[arg-type]
            warnings=tuple(sorted(set(warnings))),
        )
        return ExtractionResult(
            markdown=markdown, index=root,
            tables=tuple(tables_out), assets=tuple(assets), meta=meta,
        )


def _insert_after_page_anchor(
    md_lines: list[str], page: int, *items: str
) -> None:
    """Insert items right after the section anchor that owns ``page``.

    Looks for ``<a id="sec-{page:04d}"></a>`` first (page_fallback /
    1-per-page layouts), otherwise the first section anchor at or after
    that page. Appends to the end if nothing matches.
    """
    needle = f'<a id="sec-{page:04d}"></a>'
    for i, line in enumerate(md_lines):
        if line == needle:
            insert_at = min(i + 3, len(md_lines))
            for offset, item in enumerate(items):
                md_lines.insert(insert_at + offset, item)
            md_lines.insert(insert_at + len(items), "")
            return
    for item in items:
        md_lines.append(item)
    md_lines.append("")
