"""PPTX adapter using python-pptx. Spec §6.

v0.2 (sp2): detect native PowerPoint Sections via raw XML when present and
expose them as a level=1 layer above slides. Falls back to the v0.1 flat
slide list when the .pptx has no sections.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import pptx as _pptx

from ..contracts import ExtractionResult, SectionNode
from ._common import make_meta

_PPTX_VERSION = getattr(_pptx, "__version__", "unknown")

# OOXML namespaces used by PowerPoint sections (Office 2010+ feature).
_NS = {
    "p": "http://schemas.openxmlformats.org/presentationml/2006/main",
    "p14": "http://schemas.microsoft.com/office/powerpoint/2010/main",
}


def _detect_sections(prs) -> list[tuple[str, list[int]]] | None:
    """Return [(section_name, [slide_idx_1based, ...]), ...] or None.

    Sections are stored in `ppt/presentation.xml` under
    `<p:extLst><p:ext uri="{521415D9-...}"><p14:sectionLst>`. python-pptx
    has no public API for this as of 1.0.2, so we walk the raw XML.
    """
    root = prs.element  # lxml Element for the <p:presentation> root
    section_list = root.find(".//p14:sectionLst", _NS)
    if section_list is None:
        return None
    # Build map of slide_id -> 1-based slide index from the in-memory slide order.
    id_to_idx: dict[int, int] = {}
    for idx, slide in enumerate(prs.slides, start=1):
        try:
            id_to_idx[slide.slide_id] = idx
        except Exception:
            continue
    result: list[tuple[str, list[int]]] = []
    for section in section_list.findall("p14:section", _NS):
        name = section.get("name") or "(Unnamed Section)"
        indices: list[int] = []
        for sid_elem in section.findall("p14:sldIdLst/p14:sldId", _NS):
            raw = sid_elem.get("id")
            if raw is None:
                continue
            try:
                sid = int(raw)
            except ValueError:
                continue
            if sid in id_to_idx:
                indices.append(id_to_idx[sid])
        if indices:
            result.append((name, sorted(indices)))
    return result if result else None


class PptxAdapter:
    name = "pptx"
    version = "0.2"
    extensions = (".pptx",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        prs = _pptx.Presentation(str(src))
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        md_lines: list[str] = [
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->",
            "",
        ]

        # Collect per-slide content first (title, body markdown lines, anchor).
        slide_records: list[tuple[str, str, list[str]]] = []  # (title, anchor, md_chunks)
        for i, slide in enumerate(prs.slides, start=1):
            title = ""
            if slide.shapes.title is not None:
                title = (slide.shapes.title.text or "").strip()
            if not title:
                title = f"Slide {i}"
            anchor = f"sec-{i:04d}"
            chunks: list[str] = []
            for shape in slide.shapes:
                if shape == slide.shapes.title:
                    continue
                if shape.has_text_frame and shape.text_frame.text.strip():
                    chunks.append(shape.text_frame.text.strip())
            if slide.has_notes_slide:
                notes = slide.notes_slide.notes_text_frame.text.strip()
                if notes:
                    for line in notes.splitlines():
                        chunks.append(f"> Note: {line}")
            slide_records.append((title, anchor, chunks))

        sections = _detect_sections(prs)
        children: list[SectionNode] = []
        if sections:
            outline_source = "pptx_section"
            # Build root -> section -> slide tree, level 1 = section, level 2 = slide.
            for sec_counter, (sec_name, slide_indices) in enumerate(sections, start=1):
                sec_anchor = f"sec-grp-{sec_counter:04d}"
                md_lines.append(f'<a id="{sec_anchor}"></a>')
                md_lines.append(f"# {sec_name}")
                md_lines.append("")
                grandchildren: list[SectionNode] = []
                for slide_idx in slide_indices:
                    title, anchor, chunks = slide_records[slide_idx - 1]
                    md_lines.append(f'<a id="{anchor}"></a>')
                    md_lines.append(f"## {title}")
                    md_lines.append("")
                    for c in chunks:
                        md_lines.append(c)
                        md_lines.append("")
                    grandchildren.append(SectionNode(
                        node_id=f"{sec_counter:04d}-{slide_idx:04d}",
                        title=title, level=2,
                        page_start=slide_idx, page_end=slide_idx,
                        anchor=anchor, language="und",
                    ))
                children.append(SectionNode(
                    node_id=f"{sec_counter:04d}",
                    title=sec_name, level=1,
                    page_start=slide_indices[0], page_end=slide_indices[-1],
                    anchor=sec_anchor, language="und",
                    children=tuple(grandchildren),
                ))
        else:
            outline_source = "heading_style"
            for i, (title, anchor, chunks) in enumerate(slide_records, start=1):
                md_lines.append(f'<a id="{anchor}"></a>')
                md_lines.append(f"# {title}")
                md_lines.append("")
                for c in chunks:
                    md_lines.append(c)
                    md_lines.append("")
                children.append(SectionNode(
                    node_id=f"{i:04d}", title=title, level=1,
                    page_start=i, page_end=i, anchor=anchor, language="und",
                ))

        total = max(len(slide_records), 1)
        root = SectionNode(
            node_id="0000", title=src.stem, level=0,
            page_start=1, page_end=total,
            anchor="", language="und", children=tuple(children),
        )
        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"python-pptx": _PPTX_VERSION},
            outline_source=outline_source,  # type: ignore[arg-type]
            outline_confidence="high",
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=(), assets=(), meta=meta
        )
