"""PPTX adapter using python-pptx. Spec §6."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pptx as _pptx

from ..contracts import ExtractionResult, SectionNode
from ._common import make_meta

_PPTX_VERSION = getattr(_pptx, "__version__", "unknown")


class PptxAdapter:
    name = "pptx"
    version = "0.1"
    extensions = (".pptx",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        prs = _pptx.Presentation(str(src))
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        md_lines: list[str] = [
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->",
            "",
        ]
        children: list[SectionNode] = []
        for i, slide in enumerate(prs.slides, start=1):
            title = ""
            if slide.shapes.title is not None:
                title = (slide.shapes.title.text or "").strip()
            if not title:
                title = f"Slide {i}"
            anchor = f"sec-{i:04d}"
            md_lines.append(f'<a id="{anchor}"></a>')
            md_lines.append(f"# {title}")
            md_lines.append("")
            for shape in slide.shapes:
                if shape == slide.shapes.title:
                    continue
                if shape.has_text_frame and shape.text_frame.text.strip():
                    md_lines.append(shape.text_frame.text.strip())
                    md_lines.append("")
            if slide.has_notes_slide:
                notes = slide.notes_slide.notes_text_frame.text.strip()
                if notes:
                    for line in notes.splitlines():
                        md_lines.append(f"> Note: {line}")
                    md_lines.append("")
            children.append(SectionNode(
                node_id=f"{i:04d}", title=title, level=1,
                page_start=i, page_end=i, anchor=anchor, language="und",
            ))
        total = max(len(children), 1)
        root = SectionNode(
            node_id="0000", title=src.stem, level=0,
            page_start=1, page_end=total,
            anchor="", language="und", children=tuple(children),
        )
        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"python-pptx": _PPTX_VERSION},
            outline_source="heading_style",
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=(), assets=(), meta=meta
        )
