"""XLSX adapter using openpyxl (read_only=True, data_only=True). Spec §6."""

from __future__ import annotations

import hashlib
from pathlib import Path

import openpyxl
from openpyxl import __version__ as openpyxl_version

from ..contracts import ExtractionResult, SectionNode, TableRef
from ._common import make_meta


class XlsxAdapter:
    name = "xlsx"
    version = "0.1"
    extensions = (".xlsx",)

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        wb = openpyxl.load_workbook(str(src), read_only=True, data_only=True)
        sha = hashlib.sha256(src.read_bytes()).hexdigest()
        md_lines: list[str] = [
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->",
            "",
        ]
        children: list[SectionNode] = []
        tables: list[TableRef] = []
        warnings: list[str] = []
        anchor_count = 0
        table_count = 0

        sheet_index = 0
        for sheet_name in wb.sheetnames:
            sheet_index += 1
            ws = wb[sheet_name]
            anchor_count += 1
            sheet_anchor = f"sec-{anchor_count:04d}"
            md_lines.append(f'<a id="{sheet_anchor}"></a>')
            md_lines.append(f"# {sheet_name}")
            md_lines.append("")

            # Read all rows; treat the whole sheet as one contiguous block.
            rows: list[tuple[str, ...]] = []
            max_col = 0
            for row in ws.iter_rows(values_only=True):
                if row is None:
                    continue
                cells = tuple("" if v is None else str(v) for v in row)
                if any(c != "" for c in cells):
                    rows.append(cells)
                    max_col = max(max_col, len(cells))
            # Normalize to rectangular grid
            rows = [tuple(list(r) + [""] * (max_col - len(r))) for r in rows]

            if rows:
                table_count += 1
                t_anchor = f"tbl-{table_count:04d}"
                tables.append(TableRef(
                    anchor=t_anchor, page=sheet_index, rows_json=tuple(rows),
                    rendered_asset=None,
                ))
                md_lines.append(f'<a id="{t_anchor}"></a>')
                md_lines.append(_render_md_table(rows[:50]))
                if len(rows) > 50:
                    md_lines.append(f"\n_(showing first 50 of {len(rows)} rows)_")
                md_lines.append("")

            child = SectionNode(
                node_id=f"{sheet_index:04d}",
                title=sheet_name,
                level=1,
                page_start=sheet_index,
                page_end=sheet_index,
                anchor=sheet_anchor,
                language="und",
            )
            children.append(child)
        wb.close()

        total_pages = max(sheet_index, 1)
        root = SectionNode(
            node_id="0000", title=src.stem, level=0,
            page_start=1, page_end=total_pages,
            anchor="", language="und", children=tuple(children),
        )
        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"openpyxl": openpyxl_version},
            outline_source="heading_style",
            warnings=tuple(warnings),
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=tuple(tables), assets=(), meta=meta
        )


def _render_md_table(rows: list[tuple[str, ...]]) -> str:
    if not rows:
        return ""
    header = rows[0]
    body = rows[1:]
    lines = ["| " + " | ".join(header) + " |"]
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for r in body:
        cells = list(r) + [""] * (len(header) - len(r))
        lines.append("| " + " | ".join(cells[: len(header)]) + " |")
    return "\n".join(lines)
