"""ZIP adapter: unpacks and recursively invokes the orchestrator.

The zip adapter is special: it depends on the orchestrator. To avoid a
circular import, the orchestrator passes `registry` at call time; the zip
adapter holds a registry handle and re-enters with `_nest_depth + 1`.
"""

from __future__ import annotations

import hashlib
import zipfile
from pathlib import Path

from ..contracts import ExtractionResult, SectionNode
from ._common import make_meta


class ZipAdapter:
    name = "zip"
    version = "0.1"
    extensions = (".zip",)

    def __init__(self, child_registry=None, nest_depth: int = 0) -> None:
        self._registry = child_registry
        self._depth = nest_depth

    def extract(self, src: Path, out_dir_tmp: Path) -> ExtractionResult:
        warnings: list[str] = []
        children: list[SectionNode] = []
        sha = hashlib.sha256(src.read_bytes()).hexdigest()

        if self._depth >= 5:
            warnings.append(f"zip.too_nested:depth={self._depth + 1}")
            md = (
                f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->\n\n"
                '<a id="sec-0001"></a>\n# (zip too nested)\n'
            )
            root = SectionNode(
                node_id="0000", title=src.stem, level=0,
                page_start=1, page_end=1, anchor="", language="und",
                children=(SectionNode(
                    node_id="0001", title="too nested", level=1,
                    page_start=1, page_end=1, anchor="sec-0001", language="und",
                ),),
            )
            return ExtractionResult(
                markdown=md, index=root, tables=(), assets=(), meta=make_meta(
                    src=src, adapter_name=self.name, adapter_version=self.version,
                    tool_versions={"stdlib_zipfile": "1"}, outline_source="page_fallback",
                    warnings=tuple(warnings),
                ),
            )

        unpacked = out_dir_tmp / "_unpacked"
        unpacked.mkdir(parents=True, exist_ok=True)
        try:
            with zipfile.ZipFile(src) as zf:
                for info in zf.infolist():
                    if info.flag_bits & 0x1:
                        warnings.append(f"zip.encrypted:{info.filename}")
                        continue
                    zf.extract(info, str(unpacked))
        except zipfile.BadZipFile:
            warnings.append("zip.encrypted:unreadable")

        # Recurse via orchestrator.
        from ..orchestrator import run as orch_run
        report = orch_run(
            unpacked,
            registry=self._registry,
            _nest_depth=self._depth + 1,
        )

        # Build aggregator section tree from child main.md files.
        kb_dir = unpacked / "kb"
        idx = 0
        md_lines = [
            f"<!-- generated by kb-extract; do not edit; source_sha256: {sha} -->",
            "",
        ]
        if kb_dir.exists():
            for child_main in sorted(kb_dir.rglob("main.md")):
                idx += 1
                rel = child_main.relative_to(unpacked).as_posix()
                anchor = f"sec-{idx:04d}"
                md_lines.append(f'<a id="{anchor}"></a>')
                md_lines.append(f"# {child_main.parent.name}")
                md_lines.append("")
                md_lines.append(f"See `{rel}` (extracted from zip member).")
                md_lines.append("")
                children.append(SectionNode(
                    node_id=f"{idx:04d}", title=child_main.parent.name,
                    level=1, page_start=idx, page_end=idx, anchor=anchor,
                    language="und",
                ))

        if not children:
            anchor = "sec-0001"
            md_lines.append(f'<a id="{anchor}"></a>')
            md_lines.append(f"# {src.stem}")
            md_lines.append("")
            md_lines.append(f"(zip contained {report.skipped_count} unsupported file(s))")
            md_lines.append("")
            children.append(SectionNode(
                node_id="0001", title=src.stem, level=1,
                page_start=1, page_end=1, anchor=anchor, language="und",
            ))

        total = max(len(children), 1)
        root = SectionNode(
            node_id="0000", title=src.stem, level=0,
            page_start=1, page_end=total,
            anchor="", language="und", children=tuple(children),
        )
        markdown = "\n".join(md_lines) + "\n"
        meta = make_meta(
            src=src,
            adapter_name=self.name,
            adapter_version=self.version,
            tool_versions={"stdlib_zipfile": "1"},
            outline_source="page_fallback",
            warnings=tuple(sorted(set(warnings))),
        )
        return ExtractionResult(
            markdown=markdown, index=root, tables=(), assets=(), meta=meta,
        )
